### ISSUE TITLE
Turn logging off, silent mode?

### ISSUE THREAD

**Issue by jshier** [fastlane/scan#10]
I'd like the option to turn logging off entirely, as well as most of the command line output. I don't need to see what files are building or the other information most of the time, just the warnings or errors.

**Comment by KrauseFx** [comment]
Is there a way to only print warnings when in `xcpretty`? How would you approach this?

**Comment by xfreebird** [comment]
May be something like this `xcodebuild .. | xcpretty ..  2>&1 /path/to/file`, no logging at all :)

**Comment by jshier** [comment]
Sorry, I'm not familiar with the capabilities of `xcpretty`. This was more of a general feature request. Ideally, I'd like to just see the major steps in the build process (e.g. "Building APP", "Testing APP") along with errors or warnings, with no requirement to have a log file. If I need additional output to diagnose an issue I should just be able to run again with the verbosity turned up.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1946. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
