### ISSUE TITLE
Exit status: 65

### ISSUE THREAD

**Issue by tspecht** [fastlane/scan#102]
Hi guys,

I'm still trying to run scan and, all of a sudden, the Segmentation Fault 11 magically disappeared. Instead now I'm having a different issue:

```
scan(
      workspace: "MyApp.xcworkspace",
      scheme: "MyAppTests",
      device: "iPhone 6s",
      clean: true,
      code_coverage:true
    )
```

```
▸ Running script 'Copy Pods Resources'
▸ Running script 'Embed Pods Frameworks'
▸ Touching MyAppTests.xctest
** TEST FAILED **
ERROR [2016-03-01 15:46:39.65]: Exit status: 65
WARN [2016-03-01 15:46:39.66]: Variable Dump:
INFO [2016-03-01 15:46:39.66]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
ERROR [2016-03-01 15:46:39.66]: Error building/testing the application - see the log above
```

In Xcode I can run the tests just fine including code coverage being generated. Any hints?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1926. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
