### ISSUE TITLE
Add branch name to slack notification

### ISSUE THREAD

**Issue by nvh** [fastlane/scan#14]
It would be nice if the notification in slack (optionally) shows the branch name that the tests were run with.

**Comment by KrauseFx** [comment]
Not as easy as it sounds, as this requires the developer to use git then.

**Comment by iainsmith** [comment]
What about only displaying the branch name if git is installed and the tests are being run in the repo?

**Comment by RobDay** [comment]
Another means of solving this would be to allow a custom message to be attached to the existing slack message.  Then, each user could pass in a branch name, commit author, or their favorite color...it wouldn't matter.

**Comment by RobDay** [comment]
This isn't incredibly ideal, but what would you thoughts be around something like:

```
if Scan.config[:slack_custom_message]
        attachments << {
          text: Scan.config[:slack_custom_message].to_s
        }
      end
```

It doesn't do anything magically to pull the branch or any other repository information, but it allows the caller to append :some: custom information to the message.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1945. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
