### ISSUE TITLE
Add support to share test results for use in other actions

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/scan#57]
It would be great if the tests results were shared so they could be used in other actions to allow for keeping analytics or forming custom messages to team chat.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1937. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
