### ISSUE TITLE
Adding a timeout option

### ISSUE THREAD

**Issue by n4me1ess** [fastlane/scan#67]
I am running XC UI tests. Often they are stucking because of simulator is not responding. The scan process  wait a long time. **Is there some way to terminate testing by timeout and generate report as is?**
Also, My console output says me nothing about some problem with sim:
`[...]testRemoveUnsentItem (60.486 seconds)
2015-12-23 20:20:07.946 xcodebuild[61490:7264664] [MT] IDETestOperationsObserverDebug: (2CDF552D-23BF-4484-87CF-355405801581) Beginning test session 2CDF552D-23BF-4484-87CF-355405801581 with Xcode 7C62b on target <DVTiPhoneSimulator: 0x7fdae6796a40> {
SimDevice: SimDevice : iPad 2 (A09BF579-8C13-418D-B035-BAD8A29C0BEE) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPad-2 } runtime={ SimRuntime : 9.2 (13C70) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 }
} (9.2 (13C70))`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1936. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
