### ISSUE TITLE
Returning the test result

### ISSUE THREAD

**Issue by dalu93** [fastlane/scan#72]
Hi,
Is there a way to manage the test result directly on `Fasfile`? For example, I was expecting there was a variable into `lane_context`, but I can't find it.
This is what I want to do

```
scan(
    ...
)

if test_result
    testflght(
        ...
    )
end
```

**Comment by KrauseFx** [comment]
Sorry, not possible right now

**Comment by joshrlesch** [comment]
Could you point me in the right direction an how you would add this feature, I would like to take a stab at it?

**Comment by KrauseFx** [comment]
What kind of information do you want to access from within fastlane?

**Comment by dalu93** [comment]
Sorry for the late response. It could be useful to know which is the result (successful, build error, etc..)

**Comment by kdawgwilk** [comment]
:+1:

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1935. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
