### ISSUE TITLE
Integration with OCLint?

### ISSUE THREAD

**Issue by beloso** [fastlane/scan#74]
`xctool` has a reporter option to generate `compile_commands.json`that can be used by `OCLint`

Does `scan` offer the same option? How do I achieve that?

**Comment by KrauseFx** [comment]
What do you use it for?

**Comment by beloso** [comment]
Sorry, I did not understand the question.

What are you referring to? What do I use the reporter option for?

I use that to generate the `compile_commands.json` and feed that to `oclint` for it to work.

I know that I can use `xctool` for this effect, but I would rather use `scan`.

**Comment by beloso** [comment]
Is this being considered?

I think it would be enough to support the "--reporter" flag from `xctest`

(I think, I don't know a lot about these tools)

**Comment by daniel-beard** [comment]
@tiagomartinho OCLint now recommends the use of xcpretty (see: http://docs.oclint.org/en/stable/manual/oclint-xcodebuild.html)

@KrauseFx if there was support for passing additional arguments to xcpretty, like similar to this option:

```
-x, --xcargs STRING  Pass additional arguments to xcodebuild. Be sure to quote the setting names and values e.g. OTHER_LDFLAGS="-ObjC -lstdc++"
(SCAN_XCARGS)
```

then integration with OCLint would be simple.

**Comment by daniel-beard** [comment]
This is simple enough that I'd like to have a go at implementing.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1934. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
