### ISSUE TITLE
App screenshots of failed steps

### ISSUE THREAD

**Issue by pavelshadrin** [fastlane/scan#87]
When UI tests are run locally inside Xcode, it's very useful to be able to see the screenshots of the app right before the UI test case fails:
<img width="291" alt="screen shot 2016-02-04 at 19 50 01" src="https://cloud.githubusercontent.com/assets/10427842/12820453/918fa540-cb78-11e5-956c-f9ebc80c9fd3.png">

But if UI tests are run with Fastlane or xcodebuild, only a derived data folder can be specified that will contain the test summary and a bunch of screenshots. The test summary plist has the failureSummaries fields, but I find it impossible to map this event to the corresponding screenshot. 

It would be great if 'scan' had an ability to retrieve app screenshots corresponding to failed steps.

**Comment by KrauseFx** [comment]
Yeah, that sounds like a cool idea :+1:

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1932. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
