### ISSUE TITLE
Is it possible to run individual test case/test class?

### ISSUE THREAD

**Issue by kinwahlai** [fastlane/scan#90]
Is it possible to run individual test case/test class? like -only in xctool

Darren

**Comment by KrauseFx** [comment]
Sorry, no, currently only the complete test suite

**Comment by AnneTheAgile** [comment]
ty @KrauseFx  for a great suite of tools. I would love to be able to run individual items as well. 
FYI, here is the github reference for xctool; https://github.com/facebook/xctool

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1931. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
