### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by tspecht** [fastlane/scan#98]
Hi guys,

I tried to use scan() today to run my tests but unfortunately they are failing with "Segmentation Fault: 11". I had xctool in use previously which is running the same test suite just fine :(

```
Testing failed:
Command failed due to signal: Segmentation fault: 11
** TEST FAILED **


The following build commands failed:
CompileSwift normal x86_64 /Users/myUser/Documents/Code/SomeClass.swift
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
```

Any ideas on how to fix this?

**Comment by vpolouchkine** [comment]
Can you please share the full log?

**Comment by mfurtak** [comment]
Hi @tspecht - thanks for the report :+1: 

Can you please provide some more information about your setup? It would be good to know your:
- Mac OS version
- Xcode version
- fastlane version
- scan version

Also, if you can provide the full command output when running with the `--verbose` flag, that would be :100:!

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1927. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
